### ISSUE TITLE
Bottom sheet blocks inner scroll/gestures

### ISSUE THREAD

**Issue by ValeriyJefimov** [lucaszischka/BottomSheet#47]
Hi @LucasMucGH, thanx for an awesome lib.

But I have faced a major issue on the newest build, when trying to add horizontal scroll or drag at BS content.

Sample code:

```
struct Content: View {
    
    @State var bottomSheetPosition: BottomSheetPosition = .bottom

    var colors: [Color] = [
        .blue, .black, .gray, .green, .orange, .pink, .yellow
    ]
    
    var scrollContent: some View {
        ScrollView(.horizontal) {
            HStack {
                ForEach(colors, id: \.self) {
                    $0.frame(width: 100)
                }
            }
        }
        .frame(height: 300)
        .padding([.trailing, .leading], 20)
    }
    
    var body: some Scene {
            scrollContent
                .bottomSheet(bottomSheetPosition: self.$bottomSheetPosition,
                             options: [.appleScrollBehavior, .noBottomPosition]) {
                    scrollContent
                }
    }
}

```

And video:
https://drive.google.com/file/d/1wp2V94RMepHBi6uRKhEpWE1kaOiCS-17/view?usp=sharing

On the prev version I have fixed it with just adding an option to use simultaneous gesture, but now it doesn't work.

Thanx.

**Comment by LucasMucGH** [comment]
Yes DragGesture is not working at all or as expected. This issue is not caused by my libary, but instead by ScrollView itself: https://stackoverflow.com/questions/57700396/adding-a-drag-gesture-in-swiftui-to-a-view-inside-a-scrollview-blocks-the-scroll

The horizontal scroll issue is caused by the implementation of the `.appleScrollBehavior` option. Unfortunately there is nothing at the time I can do to fix it (as to my knowledge), because of the limitations of SwiftUI. The current approach is mainly based on buggy workarounds, because otherwise it wouldn’t work at all.
Therefore, i will probably remove the `.appleScrollBehaviour` soon.

So to answer your question: please remove the`.appleScrollBehavior` option. If the issue persist, I can reopen this, but otherwise there is nothing I can do to fix it.

**Comment by ValeriyJefimov** [comment]
@LucasMucGH  So will you remove the ability to display content with height more than overlay's?

**Comment by LucasMucGH** [comment]
No i will remove `.appleScrollBehaviour`. This option does the following:
- Puts the mainContent in a ScrollView
- Disables scroll, except in the `.top` position
- When the scroll offset is < 0 the BottomSheet gets dragged down (instead of scrolling)

If you want you can still use a ScrollView and put any content inside, as before. Only the above option gets removed.

**Comment by diegorc1312** [comment]
You could use .simultaneousGesture(DragGesture())

https://developer.apple.com/documentation/swiftui/simultaneousgesture

**Comment by lucaszischka** [comment]
No `.simultaneousGesture(DragGesture())` doesn't work.

Nevertheless it should be fixed in main. Please test the changes and report any other issues found, bevor I release them

**Comment by ValeriyJefimov** [comment]
@lucaszischka Can confirm, that inner scrolling is not blocked now.
